name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: '17.3.0'
      - name: Dummy KV DB
        run: |
          ls
          cd code/kv_bash
          source kv.sh
          kset foo bar
          kget foo
          kget bar
      - name: Build Images
        run: |
          cd code
          chmod +x *.sh
          ./start.sh
          ./stop.sh
  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ZIP build
        run: zip -r slides.zip slides
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
